{% set name = "bw_processing" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bw_processing-{{ version }}.tar.gz
  sha256: bd20780c60d0646e32b50bc3c98f55defcdc3e3507e86f1337c7e24695d63821

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=68.0
    - pip
  run:
    - python >=3.9
    - fsspec
    - morefs
    - numpy
    - pandas

test:
  imports:
    - bw_processing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/bw_processing
  summary: Tools to create structured arrays in a common format
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/bw_processing

extra:
  recipe-maintainers:
    - cmutel
    - xylar
