{% set name = "bw_processing" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bw_processing-{{ version }}.tar.gz
  sha256: 225b7afbe5d29c0815d49ce41829c1d5aa05edb6e9d16cdd0fe9cdefba05041e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.0
    - pip
  run:
    - python >={{ python_min }}
    - fsspec
    - morefs
    - numpy
    - pandas

test:
  imports:
    - bw_processing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brightway-lca/bw_processing
  summary: Tools to create structured arrays in a common format
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/bw_processing

extra:
  recipe-maintainers:
    - cmutel
    - xylar
