{% set name = "bw_processing" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 037488e676d92cedad6c694ee27ac321258775e465c6dd1a023e6a70855613ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - fs
    - numpy
    - pandas
    - python >=3.5

test:
  imports:
    - bw_processing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/bw_processing
  summary: Tools to create structured arrays in a common format
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/bw_processing

extra:
  recipe-maintainers:
    - cmutel
    - xylar
